language: php

php:
  - 7
  - 7.1
  - hhvm

install:
  - composer install

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - php vendor/bin/phpcs --standard=PSR2 ./src ./tests

matrix:
  allow_failures:
    - php: hhvm
